stages:
  
  data_load:
    cmd: python stages/data_load.py
    deps:
    - stages/data_load.py
    params:
    - data_load

  train:
    cmd: python stages/train.py
    deps:
    - stages/train.py
    params:
    - train

  data_load_with_preset:
    cmd: python stages/data_load_with_preset.py
    deps:
    - stages/data_load_with_preset.py
    params:
    - run_mode
    - data_load
